4. Learning ASP.NET Core/3. MVC Applications/mvc-app/Models/EngineeringDepartment.cs
namespace mvc_app.Models;

public class EngineeringDepartment
{
    public string[] CurrentSoftwareProjects { get; set; }

    public EngineeringDepartment()
    {
        // retrive data from DB or web service
        // hardcode for example
        CurrentSoftwareProjects = [
            "Project A",
            "Project B",
            "Project C",
            "Project D",
            "Project E"
    ];
    }
}

4. Learning ASP.NET Core/3. MVC Applications/mvc-app/Models/ErrorViewModel.cs
namespace mvc_app.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

4. Learning ASP.NET Core/3. MVC Applications/mvc-app/Controllers/EngineeringController.cs
// Created with: dotnet new mvccontroller -n EngineeringController -o Controllers --namespace mvc_app.Controllers
using Microsoft.AspNetCore.Mvc;
using mvc_app.Models;

namespace mvc_app.Controllers
{
    public class EngineeringController : Controller
    {
        // GET: EngineeringController
        public ActionResult Index()
        {
            return View();
        }

        // Notice that these return ActionResults, instead of IActionResults as in HomeController
        // This is an abstract class that is implemented by the IActionResult interface 
        public ActionResult CurrentProjects()
        {
            // Finish this in the next lesson
            var engineeringDepartment = new EngineeringDepartment();
            // Because this uses the EngineeringController, it will check the Views folder for "Engineering" first, then "Shared"
            return View(engineeringDepartment);
        }


    }
}

4. Learning ASP.NET Core/3. MVC Applications/mvc-app/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using mvc_app.Models;

namespace mvc_app.Controllers;

// By convention, includes "Controller" in the class name and extends the Controller base
public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    // These are actions that respond to HTTP requests
    // This will handle /index for instance
    public IActionResult Index()
    {
        // Handle any business logic here
        // Then return a view; this will look for index.cshtml in the Home folder first, then the Shared folder
        return View();

        // This can be overloaded to return a different view if needed, e.g.
        // return View("AnotherView");

        // Or overload the View to return a different model, see the Error action below
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        // Overloaded to return a different view with a model
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

4. Learning ASP.NET Core/3. MVC Applications/mvc-app/Views/Engineering/CurrentProjects.cshtml
<h3>Current Software Projects</h3>
<ul>
    @foreach(var project in @Model.CurrentSoftwareProjects) {
        <li>@project</li>
    }
</ul>

4. Learning ASP.NET Core/3. MVC Applications/mvc-app/Views/Engineering/Index.cshtml
<h3>Welcome to the Engineering Department web page!</h3>

4. Learning ASP.NET Core/3. MVC Applications/mvc-app/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - mvc_app</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/mvc_app.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">mvc_app</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Engineering" asp-action="Index">Engineering Dpt</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Engineering" asp-action="CurrentProjects">Current Projects</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - mvc_app - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>